apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-node
    spec:
      containers:
        - name: hello-node
          image: ppc64le/hello-node
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regsecret
      nodeSelector:
        beta.kubernetes.io/arch: ppc64le
